trace.lo: /web/code/phptrace-master/extension/trace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/trace.c -o trace.lo 
common/trace_comm.lo: /web/code/phptrace-master/extension/common/trace_comm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/common/trace_comm.c -o common/trace_comm.lo 
common/trace_ctrl.lo: /web/code/phptrace-master/extension/common/trace_ctrl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/common/trace_ctrl.c -o common/trace_ctrl.lo 
common/trace_mmap.lo: /web/code/phptrace-master/extension/common/trace_mmap.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/common/trace_mmap.c -o common/trace_mmap.lo 
common/trace_type.lo: /web/code/phptrace-master/extension/common/trace_type.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/common/trace_type.c -o common/trace_type.lo 
common/trace_filter.lo: /web/code/phptrace-master/extension/common/trace_filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/common/trace_filter.c -o common/trace_filter.lo 
deps/sds/sds.lo: /web/code/phptrace-master/extension/deps/sds/sds.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/web/code/phptrace-master/extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /web/code/phptrace-master/extension/deps/sds/sds.c -o deps/sds/sds.lo 
$(phplibdir)/trace.la: ./trace.la
	$(LIBTOOL) --mode=install cp ./trace.la $(phplibdir)

./trace.la: $(shared_objects_trace) $(TRACE_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_trace) $(TRACE_SHARED_LIBADD)

